In [1]:
import numpy as np
from mfe.dsp import generate_features

from os.path import dirname, join as pjoin
from scipy.io import wavfile
import scipy.io
import warnings
warnings.filterwarnings('ignore')

<h3><b>Load File and Raw Features Extraction

In [2]:
raw_features = wavfile.read("../dataset/test_audio.wav")

In [3]:
raw_features = np.array(raw_features[1].astype('int'))

In [4]:
raw_features

array([ 3158, -2706, -4139, ..., -2373, -1818,   285])

In [5]:
print(raw_features.shape)

(16000,)


<h2><b>Feature Extraction Using MFE

In [6]:
result = generate_features(implementation_version=3, 
                               draw_graphs=False, 
                               raw_data=raw_features, 
                               axes=[""],
                               sampling_freq=16000,
                               frame_length=0.032,
                               frame_stride=0.016,
                               num_filters=40,
                               fft_length=256,
                               low_frequency=300,
                               high_frequency=0,
                               win_size=101,
                               noise_floor_db=-52)
print(result)

{'features': [0.12109375, 0.140625, 0.140625, 0.109375, 0.109375, 0.11328125, 0.12890625, 0.12890625, 0.0625, 0.1328125, 0.1328125, 0.125, 0.1640625, 0.14453125, 0.10546875, 0.015625, 0.0546875, 0.14453125, 0.25390625, 0.2421875, 0.2265625, 0.26953125, 0.29296875, 0.28515625, 0.25, 0.26171875, 0.25, 0.33203125, 0.21484375, 0.34375, 0.47265625, 0.47265625, 0.70703125, 0.69140625, 0.5078125, 0.4609375, 0.45703125, 0.46875, 0.71484375, 0.70703125, 0.203125, 0.19921875, 0.19921875, 0.19921875, 0.19921875, 0.2265625, 0.20703125, 0.20703125, 0.21484375, 0.20703125, 0.20703125, 0.203125, 0.2265625, 0.2265625, 0.19921875, 0.2734375, 0.23828125, 0.234375, 0.265625, 0.30078125, 0.23828125, 0.25, 0.265625, 0.31640625, 0.25, 0.30078125, 0.34765625, 0.3203125, 0.34765625, 0.3828125, 0.5703125, 0.5390625, 0.71875, 0.69921875, 0.48046875, 0.39453125, 0.29296875, 0.35546875, 0.6953125, 0.69921875, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.015625, 0.03515625, 0.03515625, 0.0, 0.0, 0.01171875, 0.1445312

In [7]:
mfe_feature = np.array(result['features'])

In [8]:
mfe_feature[:40]

array([0.12109375, 0.140625  , 0.140625  , 0.109375  , 0.109375  ,
       0.11328125, 0.12890625, 0.12890625, 0.0625    , 0.1328125 ,
       0.1328125 , 0.125     , 0.1640625 , 0.14453125, 0.10546875,
       0.015625  , 0.0546875 , 0.14453125, 0.25390625, 0.2421875 ,
       0.2265625 , 0.26953125, 0.29296875, 0.28515625, 0.25      ,
       0.26171875, 0.25      , 0.33203125, 0.21484375, 0.34375   ,
       0.47265625, 0.47265625, 0.70703125, 0.69140625, 0.5078125 ,
       0.4609375 , 0.45703125, 0.46875   , 0.71484375, 0.70703125])

In [9]:
from numpy import save
# define data
data = mfe_feature
# save to npy file
save('data.npy', data)

In [10]:
data = np.load('y_train_mfe.npy')[:,0]
print(data)

[2 3 2 ... 1 1 1]


In [11]:
data1 = data.reshape(75, 40)

In [12]:
import sys
import numpy as np

with np.printoptions(threshold=sys.maxsize):
    print(data1)

[[2 3 2 2 5 1 1 1 1 1 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5
  5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5
  5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5
  5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5
  5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5
  5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5
  5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5
  5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5
  5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5
  5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5
  5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5
  5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5